### ISSUE TITLE
youtube-dl support

### ISSUE THREAD

**Issue by Marbellasaad** [Onestay/CR-Unblocker#12]
Hello,sorry if it isn't related to the extension. But since you developed this for CR i think you could help me.

When i try to use youtube-dl to download some CR content it say this : https://puu.sh/ve87t/33f33c3b60.png

It's normal,so here is my question,do you know how i could use your extension to fix this problem ? Like getting an US session ID.

Thanks in advance.

**Comment by Onestay** [comment]
Sorry, I have no idea, how the youtube-dl program works. I've looked into it on GitHub and it's written in Python from which I have no knowledge. Also, my time at the moment is fairly limited. 

I'll leave this issue open. Maybe there is somebody else wanting to do this.

**Comment by andryr** [comment]
With youtube-dl you can use a custom cookie file so it should work
See [this](https://github.com/rg3/youtube-dl/issues/11572)

**Comment by GovetaXV** [comment]
Just add a Copy your browser cookies using cookie.txt and add them to youtube-dl using --cookie [txt file with cookies]

**Comment by ratchetfreak** [comment]
it'd be nice if a script existed to create a cookie.txt compatible with youtube-dl or modify an existing one.
