### ISSUE TITLE
New maintainer for the extension needed

### ISSUE THREAD

**Issue by Onestay** [Onestay/CR-Unblocker#22]
My time at the moment is fairly limited. I'm willing to further develop the backend but don't have any time to develop the extension. In its current state, it's pretty messy and it probably requires a rewrite. If anybody if willing to do it, please contact me.

**Comment by RubbixCube** [comment]
I'm happy to help out and put some work into the extension 👍 . Currently have plenty of time on hand...

**Comment by 999eagle** [comment]
I'd be happy to help, too, although I don't have a server in the US currently to maintain the backend.

**Comment by Onestay** [comment]
Hey, I've quickly created a slack. Would be great if we could continue discussing there.
https://cr-unblocker.slack.com/shared_invite/MTgxNzMzMzY4MjYwLTE0OTQ0NDQ0MTgtNDVjMTk2MzU3Yw

**Comment by Onestay** [comment]
Slack invite deactivated. If you want to join hit me up.
