### ISSUE TITLE
Icon opening crunchyroll instead of showing the option to save credentials

### ISSUE THREAD

**Issue by Yumeeh** [Onestay/CR-Unblocker#27]
Really weird, i saw it one one pc, moved home tried it on there, it just opened chruncyroll, then i tried reinstalling the plugin, and now its broken on both pc's.. Is this a known issue?

**Comment by RubbixCube** [comment]
We've been notified about an issue with security of accounts, one user accidentally got auto logged into another users account (by the extension). They saw this and instinctively logged out (which killed that session), upon hearing this we rolled back the extension to version 1.5 to prevent this from happening.

So until we figure out a solution to this, we think it might have to do with cloudflare caching requests, we are not publishing v2.0 features until we are certain that this bug has been fixed. We don't want to compromise the security of everyone's crunchyroll accounts.

**Comment by Yumeeh** [comment]
Aah.. my bad should have read a little more
