### ISSUE TITLE
Add an option to stop or pause the extension?

### ISSUE THREAD

**Issue by Bazalia** [Onestay/CR-Unblocker#28]
I don't always have to use the extension. Is there a way to add an option to stop the extension when I don't need it without removing it from chrome?

**Comment by Blightwidow** [comment]
You can disable the extension, but that could be a great addition.

**Comment by Onestay** [comment]
I don't really see a downside to just leaving the extension on even if you
don't need it.

**Comment by Bazalia** [comment]
The main downside is that when you don't allow the extension to have access to your crunchy credentials you keep getting logged out. If the anime that I am watching in the current season are all available in my country then I don't need to keep the extension on. Hence I prefer to leave it "off" to avoid logging in every time.

**Comment by Onestay** [comment]
Hmm, yea I see. 
I agree that would be a cool addition. I'll see what we can do

**Comment by 999eagle** [comment]
Added an option to disable switching regions without in a617277.

**Comment by Bazalia** [comment]
Great, thanks!
