### ISSUE TITLE
VRV-Unblocker

### ISSUE THREAD

**Issue by GovetaXV** [Onestay/CR-Unblocker#30]
Is it possible to Unblock VRV, as Crunchyroll is no good anymore. VRV has Crunchyroll's Content, Funimation's Content and Much More.

VRV can Be Found on VRV.CO

Using a Normal VPN, Gives very Slow Speeds, The Same Problem we used to have with Crunchyroll and The Reason for this extension.

**Comment by LynnAU** [comment]
I don't know how VRV handles region identification, and ways of getting around it. I haven't looked into it because I personally don't live in the US and I don't think any of the maintainers do either...

Here is what's presented when I go to vrv,
![](https://i.imgur.com/3iUjMGE.png)

**Comment by GovetaXV** [comment]
VRV's has Crunchyroll and More, so I think Only Crunchyroll is no good anymore.

**Comment by 999eagle** [comment]
I did some testing on VRV and it seems that there's no way of keeping a US session from outside the US. Even while logged in with a valid account you're redirected to the unavailable page as soon you're outside the US.

For now, we can just wait until VRV is available in other countries.
