### ISSUE TITLE
Is this possible on the vita's version too ?

### ISSUE THREAD

**Issue by high-sam** [Onestay/CR-Unblocker#31]
hey onestay !
first of all massive thank you for the chrome extension.
however i was wondering if there is a work around to get an american ID-session on the ps-vita app ?

**Comment by Onestay** [comment]
Hey,
sorry, but I have no idea how I would go about this. I have no idea about vita modding to inject any code or something like this. My time at the moment is fairly limited too, so I don't really have any time to research it.

**Comment by high-sam** [comment]
Fair enough , thanks for the reply !
