### ISSUE TITLE
Extension not working?

### ISSUE THREAD

**Issue by Smlf0** [Onestay/CR-Unblocker#36]
while watching anime, the video just doesnt load, its stuck in a loading phase but nothing happens.

Heres a screenshot: https://gyazo.com/30597d7378e8e18e97046dcd0ed08568

**Comment by Smlf0** [comment]
Never mind, fixed this issue by clearing cookies.

**Comment by finn-h** [comment]
CR had some server issues, so your problem might be related to that.

(Just wanted to give this little insight, even if it's fixed now)

**Comment by Smlf0** [comment]
Still doing it again :/
