### ISSUE TITLE
session id error.

### ISSUE THREAD

**Issue by kohope8** [Onestay/CR-Unblocker#38]
Think crunchy changed how they store session id just now.
Now it does not change my region.
Might need a investigation on this.

Browser: Firefox 56.0.2 (64-bit)

**Comment by Onestay** [comment]
I won't be home until later today. I'll look into it ASAP then

**Comment by kohope8** [comment]
After a quick look into the code it seems like the fetching server is down.

**Comment by Onestay** [comment]
It looks like it's an issue with the API endpoint from Crunchyroll. Nothing
we can do about that.

kohope8 <notifications@github.com> schrieb am Sa., 4. Nov. 2017, 11:43:

**Comment by greenborg** [comment]
I am getting sent to http://crunchyroll.com/videos/anime/ if you go to the main page witch is the only working one, it what to download and exe file, pretty sketchy

**Comment by Blightwidow** [comment]
Ok, crunchyroll seems to have either problems or maing quiete some changes:
 - Some pages on crunchyroll.com doesn't redirect you to www.crunchyroll and insteade download a strange .exe
 - The api from crunchyroll return a 404

They might be under attack

**Comment by Onestay** [comment]
What do you mean, download an exe?

**Comment by Blightwidow** [comment]
Try http://crunchyroll.com

**Comment by greenborg** [comment]
it whant to download ChrunchViewer.exe if i go to that, its missing www http://crunchyroll.com/

**Comment by Onestay** [comment]
It also downloads the exe on mobile for me, which means the extension has nothing to do with it. Crunchyroll is definitely behaving weird right now.

Do NOT run the exe as long as you haven't heard anything official from Crunchyroll!

**Comment by greenborg** [comment]
Fuck no its sketchy as hell man

**Comment by cAstraea** [comment]
Had this problem also. Sophos blocked it as malware. Only happens on chrome if i visit crunchyroll.com I get redirected to http://109.232.225.12/CrunchyViewer.exe -> Don't click on this

**Comment by kohope8** [comment]
Just to warn anyone who are reading this

Their site get completely spoofed. Don't execute anything.

**Comment by finn-h** [comment]
Crunchyroll is working on it, they seem experience some DNS Hijacking.

Soruce: https://twitter.com/Crunchyroll_de/status/926782599460212736
