### ISSUE TITLE
Https connection

### ISSUE THREAD

**Issue by patryk4815** [Onestay/CR-Unblocker#4]
Add https connection to your server in background_script.js
https://github.com/Onestay/CR-Unblocker/blob/master/extension/background_script.js#L4

Use https://letsencrypt.org/ , to generate free ssl

**Comment by patryk4815** [comment]
Ahh 👍  you use redirect

**Comment by Onestay** [comment]
Oh yeah, well I can change that but nginx is redirecting every request to https

**Comment by Onestay** [comment]
No fetches https by default dacff5c2f86c3b4c5e7791d9923aaf18ea9dedf3
