### ISSUE TITLE
DONT USE CRUNCHYROLL RIGHT NOW

### ISSUE THREAD

**Issue by Onestay** [Onestay/CR-Unblocker#40]
It seems like they are hacked or hijacked. It downloads an exe if you visit the site. Don't run the exe. If you already ran it perform a malware and virus check.

DONT USE CRUNCHYROLL RIGHT NOW!

**Comment by wert1234566** [comment]
When i use crunchyroll without cr unblocker everything seems to work normaly, but as soon as i try ti change my seesion id via cr unblocker i am forwarded to this crunchyviewer.exe download. Could it be, that cr unblocker itself was hacked?

**Comment by Onestay** [comment]
No, that's not the problem. The extension redirects you to http://crunchyroll.com which is the only site that downloads the exe. You are probably accessing Crunchyroll at another url. Apart from that Crunchyroll has already confirmed that they have issues.

**Comment by Onestay** [comment]
It also downloads the exe for me on mobile where browser extensions are not possible.

**Comment by wert1234566** [comment]
What a shame

**Comment by Onestay** [comment]
It's safe to use again

https://twitter.com/Crunchyroll_de/status/926850371879931904
