### ISSUE TITLE
Does this work on mobiles or just computers

### ISSUE THREAD

**Issue by TooLazyToPickANickname** [onestay/CR-Unblocker#41]
I am curious if I can use this on my phone, but couldn’t find this mentioned anywhere (_could be because I’m just bad at navigating this website but I tried_)

**Comment by finn-h** [comment]
Hi!

It is possible to install this extension on Firefox for Android. Chrome unfortunately does not support Extensions on their mobile version.

Maybe we should add a note in the readme, thoughts @onestay ?

**Comment by onestay** [comment]
Sure, I guess we could do that. Would you mind submitting a PR?

**Comment by Blightwidow** [comment]
Closing as the PR was submitted. 

As explained in the [comments](https://github.com/onestay/CR-Unblocker/pull/43), it can be installed on firefox for android, but it's usage is close to none as the HTML5 player is in beta accessible to only a handful of users and Firefox doesn't play Flash player.
