### ISSUE TITLE
Extension not working for me

### ISSUE THREAD

**Issue by Valafar123** [onestay/CR-Unblocker#42]
Hello,

I tried installing the extension, but I've had no joy getting it working thus far. I tried downloading the latest version from the Chrome Web Store, as well as installing the latest version from GitHub, in addition to clearing my cookies, but it still doesn't seem to be removing the region lock.

Is there anything I'm missing or should try? I'm sure the extension works fine normally and I'm just doing something wrong.

Cheers,

-Vala

**Comment by onestay** [comment]
Hey,

what chrome version are you on?

**Comment by onestay** [comment]
Could you try going to chrome;//extensions and enable developer mode in the top right. On the CR-Unblocker extension click on "background page" then go to the network tab and send me a picture after you visited the crunchyroll site.

**Comment by Valafar123** [comment]
Here's a screencap: https://gyazo.com/ffaf07017af8fb6c6ece1dac40a9fd38

**Comment by onestay** [comment]
all right that looks good. Could you do the same but with the console open now?

**Comment by Valafar123** [comment]
Here you are: https://gyazo.com/4506451fab0eb1349acd3b6abbb8d28b

**Comment by onestay** [comment]
you might want to change your password since you just posted your session id here. Sorry I should've told you to blur it out.

Everything looks good tho. Are you sure that your country is not changed. The flag at the bottom of the page doesn't show an american flag?

**Comment by Valafar123** [comment]
It does show the region as USA, but it still displays the "Sorry, due to licensing limitations, videos are unavailable in your region." message, and doesn't show videos from the region-locked content I'm trying to view ("Dagashi Kashi", where only Season 2 is available in my region).

This is true, regardless of whether I'm logged in or not.

**Comment by onestay** [comment]
It also shows that for me when I try to access this series. I guess it's just not available in the USA. Can you confirm that other series which were blocked in your home region are available with the unblocker?

**Comment by Valafar123** [comment]
I can confirm that other region locked content is working. I suppose you're right; it must not be available in the US either. Thanks for the help, anyway.

**Comment by onestay** [comment]
No problem. I guess the issue can be closed now.
