### ISSUE TITLE
Not Working with anime Prison School

### ISSUE THREAD

**Issue by Velken** [onestay/CR-Unblocker#44]
Link: http://www.crunchyroll.com/prison-school

**Comment by onestay** [comment]
That's because the anime is not available in the US. Can you confirm it lifts region block for other Shows which weren't available in your original region?

**Comment by Velken** [comment]
Confirm it lifts for other shows, made some research, Prison School is available for France and some French-speaking countries. Maybe add option to manually change target country of CR Unblocker?

**Comment by kohope8** [comment]
It will require to setup a new server in a vps that is located in that
country, its do-able but not a cheap solution consider it as an open source
tool.

**Comment by onestay** [comment]
Yea, basically what he said. It would require me to pay for multiple servers in multiple regions. I sadly don't have the money for that.

**Comment by onestay** [comment]
I think this can be closed for now
