### ISSUE TITLE
Could you make a Firefox-Port?

### ISSUE THREAD

**Issue by klose91** [Onestay/CR-Unblocker#5]
As the title says, would it be possible for you to create this extension for Firefox as well?
The current Firefox port used the old one with some changes to make it work with Firefox but since it used the old code it doesn't work anymore.
It would be great if you can also make a extension for Firefox.

**Comment by Onestay** [comment]
Uh... I have no knowledge of Firefox extensions but I could take a look at it. Is the old Firefox-Port open source?

**Comment by klose91** [comment]
Yes, it's also on github.
https://github.com/harrelchris/Crunchyroll-Unblocker
As far as I see it, the difference was somehow instead of chrome using browser? But dunno, haven't done any extension for browsers.

**Comment by Onestay** [comment]
I will have a look when I have some time.

**Comment by Onestay** [comment]
I have just created a PR, updating the code for the old firefox extension. Now we'll have to wait for him merging it and updating his extension.

**Comment by klose91** [comment]
Thanks for doing it, hopefully he'll look into it soon and can publish the extension.

**Comment by Ar1sC** [comment]
It's getting this error "Main server and backup server couldn't get an session id"

**Comment by Blightwidow** [comment]
The linked repository has not been updated in 5 months now and you pull request hasn't been  accepted. I think the Dev stopped working on it. 

Would it be a lot of work to release a Firefox extension of your own? I can maybe help.

**Comment by Onestay** [comment]
Didn't @999eagle publish a Firefox extension?

**Comment by Onestay** [comment]
If not, the code for the extension in the repo should be cross browser compatible. You can try it out, publish it and link it here in the repo if you want. I'd appreciate some credit in form of a link to the repo if you publish it tho.

**Comment by 999eagle** [comment]
I didn't publish a Firefox extension as I'm not primarily using Firefox and thus wouldn't catch any problems that may arise in the future. I could do that, but if someone who actually uses Firefox and already has an account for publishing would do it, that'd be better.

**Comment by Blightwidow** [comment]
So between your reply and now, I actually started to port your chrome extension to Firefox. I finished right now. The only problem I have is that the servers don't respond with CORS headers, making it impossible to fetch the session ID from the Firefox extension.

On a side note, I cleaned a bit some part of the code, I won't publish it on my github, but i can send it if you want, when i know it works

**Comment by 999eagle** [comment]
The extension is already cross-browser compatible. The current master branch was tested and confirmed working in Chrome, Firefox and Edge. The CORS headers aren't needed because the server URLs are listed in the manifest's permissions.

**Comment by Blightwidow** [comment]
I don't know if it was tested but I doubt it was completely tested.

- The "background" permissions doesn't exist in Firefox
- The error notifications cannot be displayed as you are passing directly the error _e_ in the notification instead of the message,
- The chain of promises were not flattened
- ...

I cleaned the code and commented it a bit. Will push it to my repo in a bit. Also i finally know why it didn't work on my Firefox: My cookies are disabled and that make it harder for the addon to work.

**Comment by 999eagle** [comment]
The current code is meant to work without modification in Chrome, Firefox and Edge, which is something that would break if your points were implemented.
- The background permission is still needed for other browsers.
- In line 19 of background_script.js we pass a custom error message, not the error itself and we're not calling `createError` anywhere else.
- We aren't using promises in `setCookie` as Edge doesn't support promises in those APIs.
Cleaning and commenting the code on the other hand might be a good idea.

**Comment by Blightwidow** [comment]
Okay i see the point. To bad it was not deployed in the Firefox store then.

But you're only passing the custom error if the result is not OK, not in case of Network errors. Causing a failure in the notifications if you go into the catch part of the fetch promise at line 39.

Edge implemented Promises and even corrected the performance issue they had with it in [Edge 14](https://docs.microsoft.com/en-us/scripting/javascript/reference/promise-object-javascript)

**Comment by 999eagle** [comment]
Your code shows the actual error message to the user which might be helpful for debugging. I think we could implement something like that, but for now the user always receives a generic error message as the caught exception is never passed to `createError` which shows the notification, the error is only logged to the console.

Yes, Edge does handle promises (`fetch` works with promises), but the `browser.cookies.*` APIs don't return a promise at all; they throw an error if no callback is passed. We are thinking about using a polyfill script to get rid of that callback hell, but haven't implemented it yet.

**Comment by Blightwidow** [comment]
Ok. Edge implementing stuff partially as always.

For the message, I just checked and your right. Last thing is, you are testing the content script on all urls instead of passing a regex chain corresponding to crunchyroll. Is there a reason for that ?

**Comment by Onestay** [comment]
There is. Send me your email and I'll invite you

**Comment by alzamer2** [comment]
hi about this issue, idont know if still open or you finished it
but i used those step from this [Link](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) to load the the extension from serverless branch and it worked for me

**Comment by Blightwidow** [comment]
It is still open and you could make your own pretty easily by loading them as unpackaged.

The problem is that I am the only team member using Firefox everyday. I don't have time or desires to actually put it on the addon store of firefox. Anybody wanting to actually use it or post it on the store is free to do so.

**Comment by mirh** [comment]
I like used [this](https://addons.mozilla.org/firefox/addon/chrome-store-foxified/) and chrome extension worked out of the box. 
So.. I guess it really just about putting it on the store now?

**Comment by Blightwidow** [comment]
The source code is actually compatible with Firefox, it just need to be put on the store. We just don't have a dev using Firefox as their main driver (I am, but cookies policies render the plugin useless) and therefore didn't want to put a plugin on the store that we don't use.

**Comment by mirh** [comment]
> but cookies policies render the plugin useless

? It works for me

**Comment by Blightwidow** [comment]
> ? It works for me

My firefox is heavily modified and doesn't allow any cookies. This render the plugin useless as it relies on cookies.

**Comment by finn-h** [comment]
For everyone interested in this Thread: I just uploaded the Extention for everyone to use. I will try to keep up with updated versions from this repository as soon as there are new versions available.

Feel free to direct Firefox related issues to me.

https://addons.mozilla.org/en-US/firefox/addon/crunchy-unblocker/

**Comment by Onestay** [comment]
Alright, thanks for uploading this. 
You can make a pull request, if you want, and also add it to the read me.

**Comment by Onestay** [comment]
Guess this can be closed then.
