### ISSUE TITLE
Possible solution for required trimming of session id

### ISSUE THREAD

**Issue by reconman** [Onestay/CR-Unblocker#6]
I have discovered CR unblocker today because of the non-functioning Crunchyroll unblocker. I looked through the client code and saw that you have to trim the space at the end.

The reason for this is probably the usage of console.log instead of process.stdout.write in the getId.js script. console.log always appends a \n at the end.

http://stackoverflow.com/questions/6157497/node-js-printing-to-console-without-a-trailing-newline
https://nodejs.org/api/process.html#process_process_stdout

To not break your system you would first have to update the client scripts so the linebreak is only trimmed if it really exists and then update the server so it doesn't return the linebreaks anymore.

**Comment by Onestay** [comment]
Changed in 7f0dcf48a26a06c14bd3a8901c5e8bb97dfcf902
