### ISSUE TITLE
"CR-Unblocker has encountered an error" on startup

### ISSUE THREAD

**Issue by jurchiks** [Onestay/CR-Unblocker#7]
I get a `TypeError: failed to fetch` when my PC starts up and this extension with it.
I believe this error is caused by the failing request to `fetch('https://cr.onestay.moe/getId')`, because my internet does not connect immediately after logging in, it takes a couple of seconds.
Would be nice if that could somehow be fixed (e.g. by adding a timeout of, say, 5 seconds inside `onStartup`), otherwise this alert box jumps out on every login, even though the extension works fine.

**Comment by Onestay** [comment]
This should be fixed with version 1.1.0. Do you still experience that issue?

**Comment by jurchiks** [comment]
Seems to be fixed, thanks.
