### ISSUE TITLE
Currently not working.

### ISSUE THREAD

**Issue by Onestay** [Onestay/CR-Unblocker#9]
I have no idea what's happening right now. The request module seems to be unable to send a get request to crunchyroll.com which is causing the error. The exact same script running on the server works fine on my home PC. I'll look into it and update this issue. 

**Thanks to @RubbixCube we now have a temporary workaround. I will try to fix the bug on my end asap**

**Comment by Onestay** [comment]
Edit: 
Now the script running on my home computer also gets that issue.

**Comment by jurchiks** [comment]
Crunchyroll itself seems damn slow at the moment. It also fails to load one of its own JS files (http://static.ak.crunchyroll.com/js/lang/20170301194559/cr/enUS/common.js).

**Comment by Onestay** [comment]
Saw that. 
But I think the problem is that the CloudFlare protection is giving a captcha which the module I'm using can't bypass.

**Comment by jurchiks** [comment]
I don't get a captcha anywhere...

**Comment by Onestay** [comment]
Me neither, but the server is.

**Comment by jurchiks** [comment]
LOL, now that's weird.

**Comment by Onestay** [comment]
I don't know. I receive about 1 request per 2 seconds. That means 2 requests to their website in 2 seconds. I'm not 100% sure what causes it yet.

**Comment by RubbixCube** [comment]
Re-running the script that I had saved from the very beginning. I was still able to retrieve the session IDs when re-running the script only 1-2 seconds apart from each other.

![](http://i.imgur.com/QF9TTk8.png)

**Comment by megonemad1** [comment]
could the captcha  be from when you go to the login screen and it "checks your browser"?

**Comment by RubbixCube** [comment]
Yes. That's cloudflare doing an automated check to see if you are in fact, a human.

Otherwise it gives you a captcha to prove you are not a bot...

**Comment by Onestay** [comment]
Yep, the captcha is exactly where the problem lies. I don't think there's anything I can do about that. I got it working again on my home computer but can't seem to run it on the server. Here's the full error if anyone is interested: https://cr.onestay.moe/getIddev

**Comment by Glegionar** [comment]
It doesn't work automatically, but how about we change the id manually? Does it work, or it will reset it?

**Comment by Glegionar** [comment]
Crunblocker seems to not be working also...

**Comment by Onestay** [comment]
The problem is that the server is unable to get the American session id. The extension is just changing your session id to that one the server gives you.

**Comment by RubbixCube** [comment]
Currently my script can still retrieve a session ID and it's hosted in New York. If you want, you can use it until you can figure out a solution @Onestay.

https://rubbix.net/crunchyroll/

**Comment by Onestay** [comment]
Hey, thanks for your offer,

could you make your script return a JSON object with the value "ok: true" and "sessionId: the session id" ?

Otherwise it would break compatibility.

**Comment by RubbixCube** [comment]
@Onestay The page now returns an object looking like `{"ok":true,"sessionId":"bktf51zjdrxcgsq46lq0wozp24udhvak"}`

**Comment by Onestay** [comment]
Thank you. I've just published the update for the extension. It should be on the webstore in about 30-60 minutes. I'll try to get it working for me again asap.

**Comment by DieterReinert** [comment]
@Onestay I just redownloaded it from the webstore I think you can close this issue because it now works again.

**Comment by davhuit** [comment]
Yeah, I updated it and it works fine now. But I don't think the issue should be closed, as it's just a workaround. Onestay seems to want to fix it directly on his server.

**Comment by Onestay** [comment]
I leave it open until I have fixed it on my server.

**Comment by Onestay** [comment]
Okay, it should be fixed. I will publish an update later.

@RubbixCube would be okay for you if I implement it, that when my server returns an error it tries to get the session id from your server?

**Comment by RubbixCube** [comment]
Sure. Happy to do that @Onestay, although I'm curious as to why your implementation didn't work while mine remained virtually untouched aside from the recent hickup in #11.

**Comment by Onestay** [comment]
I think it was the IP of my server being blocked from cr. If  that happens again I will use a VPN or a proxy
